### ISSUE TITLE
Type of delivery not updating on review screen when changed to phone

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MichiganLetterToLandlordReRet#25]
Per Emily: 
I edited this to change it to notification by text. After I did so the “Type of Delivery” line disappeared from the review screen. It also didn’t ask what number I texted to.
![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/32527754/d8fb3685-4d56-4a53-adf9-7e495e47bb2a)

**Comment by normon66** [comment]
I am able to duplicate this, but as far as I can tell, it should work.

If I select 'email' delivery method the first time through but still enter a phone number, when changing the delivery method to text, it _should_ show up on the updated review screen. However, if I remove the struck out text as seen below, the "Text to" does show up. 

   ![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/32527754/584d349b-999f-4902-a269-110723cce795)

This does not make any sense to me, because `other_parties[0].phone_number` has been answered, and therefore `phone_number_formatted(other_parties[0].phone_number)` should show up. For lack of a better response, I chalk this up to a DA quirk.

Not that after the new Review screen is shown, the interview _will_ ask for the landlord's number.

**Comment by ekressmiller** [comment]
Thanks for checking into it Brett! I'd be interested to know if @BryceStevenWilley has any thoughts since we might run into this on another interview and I'm still definitely getting my head around how review screens work.

**Comment by BryceStevenWilley** [comment]
Took me a while to find it, but this is happening because `other_parties[0].phone_number` is set to `depends on: type_of_delivery`. So every time someone changes the type of delivery, docassemble forgets the phone number.

It's definitely a downside of docassemble's way of asking questions. My approach to this has been to make a small separate code block that makes sure all of the relevant variables are re-calculated and re-asked if one is changed. Something like this should work for this interview:

```yaml
code: |
  if type_of_delivery == 'mailed':
    notification_address_same
  elif type_of_delivery == 'e-mailed':
    other_parties[0].email
  if defined('other_parties[0].phone_number') and other_parties[0].phone_number is None and type_of_delivery == 'texted':
    # If the phone number was skipped the first time through, ask it again
    del other_parties[0].phone_number
  other_parties[0].phone_number
  recompute_delivery = True
---
question: |
  Review your answers
review:
  ...
  - Edit:
    - type_of_delivery
    - recompute:
      - recompute_delivery
    button: |
```

Let me know if you have questions, but I think this is implementable.
