### ISSUE TITLE
Consolidate Useful information on the last screen

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MichiganLetterToLandlordReRet#7]
`letter_date_notification` and `MLH_outro_download_forms` both have useful information, but I question spreading them out over a few different screens like they. IMO, we could show all of the same info on the last screen, in context, without overwhelming the user or putting too much text there.

**Comment by normon66** [comment]
Because `letter_date_notification` is a conditional screen and only shown when it has not yet been thirty days, I will leave it separate for now. However, this did prompt me to include a short dynamic section in the instructions:

![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/32527754/83ef95d0-d276-4996-b1fb-1c658f2716f5)
   OR
![image](https://github.com/mplp/docassemble-MichiganLetterToLandlordReRet/assets/32527754/a4bc3826-cee4-4468-a611-6149dbcfb96b)
