### ISSUE TITLE
Subject Matter Question: Sending by email?

### ISSUE THREAD

**Issue by BryceStevenWilley** [mplp/docassemble-MichiganLetterToLandlordReRet#9]
Definitely out of scope for now, but I think it's worth it to look into if tenants are allowed to send this letter to their landlord in other ways, such as email or text.

Some specific things we'd want to add:
* We do let the user select their method of delivery, but don't ask for the landlord's email / put it anywhere in the letter, and the instructions only mention mail and certified mail
* We should add the user's signature if they're emailing, so they don't have to print it out

**Comment by normon66** [comment]
Good suggestions here. When this goes to Nora for review, I can include these ideas.

**Comment by normon66** [comment]
Per email response from Nora:

1) yes, if email is going to be used, the email address should be added to the letter 

2) I hesitate to add texting or WhatsApp because it isn't an established delivery method. It would likely depend on whether the person was communicating with the LL through these channels before. But to make sure we cover everyone, and don't possibly create issues for someone later, I think we stick with the methods we have.
